[package]
name = "birocrat-web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1"
fmterr = "0.1"
mlua = "0.9" # `birocrat` sets the features for us
birocrat = { version = "0.1", path = "../birocrat" }
serde_json = "1"
leptos = { version = "0.6", features = [ "csr" ] }
console_error_panic_hook = "0.1"
web-sys = "0.3"
wasm-bindgen = "0.2"

[lib]
crate-type = [ "cdylib", "rlib" ]
