[package]
name = "birocrat-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1"
fmterr = "0.1"
mlua = "0.9" # `birocrat` sets the features for us
birocrat = { version = "0.1", path = "../birocrat" }
dialoguer = "0.11"
clap = { version = "4", features = [ "derive" ] }
